# Generated by Django 5.2 on 2025-04-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_test_quiz_test_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='number_of_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='test_code',
            field=models.CharField(default='TES5TA56BX', max_length=255),
        ),
        migrations.AddField(
            model_name='test',
            name='test_duration',
            field=models.IntegerField(default=0),
        ),
    ]
