# Generated by Django 5.2 on 2025-04-18 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_test_number_of_questions_test_test_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='test_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
        ),
    ]
