# Generated by Django 5.2 on 2025-04-20 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_test_test_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('user_name', models.CharField(max_length=225)),
                ('name_teacher', models.CharField(max_length=225)),
                ('no_section', models.IntegerField(default=0)),
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreateClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=225)),
                ('name_teacher', models.CharField(max_length=225)),
                ('subject', models.TextField()),
                ('Shortcut_sub', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('class_code', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher_id', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='quiz.teacherinfo')),
            ],
        ),
    ]
