# Generated by Django 5.2 on 2025-04-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_teacherinfo_createclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinfo',
            name='name_teacher',
            field=models.CharField(max_length=225, unique=True),
        ),
    ]
