# Generated by Django 5.2 on 2025-04-20 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_teacherinfo_name_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createclass',
            name='teacher_id',
            field=models.ForeignKey(db_column='teacher_id_id', on_delete=django.db.models.deletion.CASCADE, to='quiz.teacherinfo'),
        ),
    ]
