# Generated by Django 5.2 on 2025-04-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_createclass_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherinfo',
            name='year',
            field=models.CharField(default=0, max_length=25),
        ),
    ]
