# Generated by Django 5.2 on 2025-04-21 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_teacherinfo_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('std_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.TextField(max_length=225)),
                ('std_prn', models.IntegerField()),
                ('std_sec', models.CharField(max_length=225)),
                ('no_subject', models.IntegerField()),
                ('std_created_at', models.DateTimeField(auto_now_add=True)),
                ('std_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JoinClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_cla_code', models.CharField(max_length=225)),
                ('sub_name', models.TextField(max_length=225)),
                ('std_created_at', models.DateTimeField(auto_now_add=True)),
                ('std_updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.ForeignKey(db_column='student_id_id', on_delete=django.db.models.deletion.CASCADE, to='quiz.studentinfo')),
            ],
        ),
    ]
