# Generated by Django 5.2 on 2025-04-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_studentinfo_joinclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='std_roll',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='no_subject',
            field=models.IntegerField(default=0),
        ),
    ]
