# Generated by Django 5.2 on 2025-04-21 14:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_remove_quiz_id_quiz_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_quiz',
            name='PRN',
            field=models.CharField(default=0, max_length=225),
        ),
        migrations.AddField(
            model_name='test_quiz',
            name='test_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='test_quiz',
            name='test_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
