# Generated by Django 5.2 on 2025-04-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_test_quiz_prn_test_quiz_test_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_quiz',
            name='test_created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
