# Generated by Django 5.2 on 2025-04-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_alter_test_quiz_test_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question_no',
            field=models.TextField(default=0),
        ),
    ]
