# Generated by Django 5.2 on 2025-04-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_quiz_question_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_quiz',
            name='marks',
            field=models.IntegerField(default=0),
        ),
    ]
