# Generated by Django 5.2 on 2025-04-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_test_quiz_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_quiz',
            name='std_section',
            field=models.CharField(default=0, max_length=225),
        ),
    ]
