# Generated by Django 5.2 on 2025-04-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_test_quiz_std_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test_code',
            new_name='test_code_val',
        ),
    ]
