# Generated by Django 5.2 on 2025-04-21 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_rename_test_code_test_test_code_val'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='test_code_val',
            new_name='test_code',
        ),
    ]
