# Generated by Django 5.2 on 2025-05-08 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_rename_test_code_val_test_test_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='question_no',
        ),
    ]
