# Generated by Django 5.2 on 2025-05-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_remove_quiz_question_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_quiz',
            name='marks',
        ),
    ]
