# Generated by Django 5.2 on 2025-05-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_remove_test_quiz_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_quiz',
            name='std_name',
            field=models.CharField(default=0, max_length=225),
        ),
        migrations.AlterField(
            model_name='test_quiz',
            name='user_name',
            field=models.CharField(default=0, max_length=225),
        ),
    ]
