# Generated by Django 5.2 on 2025-05-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='username',
            field=models.TextField(default=0, max_length=225),
        ),
    ]
