# Generated by Django 5.2 on 2025-05-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_result_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='std_roll',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
